CREATE TABLE users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50),
    password VARCHAR(255),
    email VARCHAR(255),
    role VARCHAR(20),
    facebook_id BIGINT(20) UNSIGNED NOT NULL,
    created DATETIME DEFAULT NULL,
    modified DATETIME DEFAULT NULL
);

CREATE TABLE events (
    id BIGINT(20) UNSIGNED PRIMARY KEY,
    name VARCHAR(512) DEFAULT NULL,
    description TEXT DEFAULT NULL,
    cover VARCHAR(512) NULL DEFAULT NULL,
    location VARCHAR(512) DEFAULT NULL,
    start_time DATETIME DEFAULT NULL,
    end_time DATETIME DEFAULT NULL,
    timezone VARCHAR(25) DEFAULT NULL,
    updated_time DATETIME DEFAULT NULL,
    is_date_only INT(1) DEFAULT NULL,
    venue_id BIGINT(20) UNSIGNED DEFAULT NULL
);

CREATE TABLE venues (
    id BIGINT(20) UNSIGNED  PRIMARY KEY,
    name VARCHAR(512) DEFAULT NULL,
    city  VARCHAR(512) DEFAULT NULL,
    country  VARCHAR(512) DEFAULT NULL,
    latitude  VARCHAR(512) DEFAULT NULL,
    longitude  VARCHAR(512) DEFAULT NULL,
    street  VARCHAR(512) DEFAULT NULL,
    zip  VARCHAR(10) DEFAULT NULL
);
